"use client";

import { useCallback, useMemo, useState } from "react";
import { Schema } from "effect";
import {
  ConnectorsResponseSchema,
  type ConnectorView,
} from "@local-studio/agent-runtime/connector-contract";
import { Button, RefreshIconButton, SearchInput, Spinner, StatusPill } from "@/ui";
import { Plus, Trash2 } from "@/ui/icon-registry";
import { ResourceDrawer, ResourceDrawerSection, ResourceFact } from "@/ui/resource-drawer";
import { ResourceLogo } from "@/ui/resource-logo";
import {
  DataRow,
  EndCell,
  HeadCell,
  IdentityCell,
  RowAction,
  StatusText,
  TableFrame,
  TableNotice,
  TableSection,
  TextCell,
} from "@/features/recipes/recipes-content/catalog-table-shell";
import { useMountSubscription } from "@/hooks/use-mount-subscription";
import { jsonBody, requestAgentJson } from "./agent-json";
import { CONNECTOR_CATALOG, renderCommandLine, type CatalogEntry } from "./connector-catalog";
import {
  ConnectorEditorDrawer,
  draftFromCatalog,
  draftFromConnector,
  emptyDraft,
  resolveSshServerPath,
  type ConnectorDraft,
} from "./connector-editor-drawer";
import { ConnectorOAuthDrawer } from "./connector-oauth-drawer";

/**
 * MCP servers, as a thing the user owns rather than a thing that arrives.
 *
 * The table lists what is registered and the exact command behind each row —
 * the command column is not a nicety, it is the answer to "what did I agree to
 * run" and it is visible without opening anything. Every path into the editor,
 * whether that is Add, a catalog entry, or clicking a row, lands on the same
 * form with the same preview and the same disabled-by-default rule.
 *
 * Rows generated by a signed-in account (`origin`) are shown read-only: they
 * are rewritten from the account each time they are read, so an edit here
 * would be silently reverted, and pretending otherwise is worse than saying so.
 */

const CONNECTOR_MIN_WIDTH = "min-w-[42rem]";

const connectorCommand = (connector: ConnectorView): string =>
  connector.transport === "stdio"
    ? renderCommandLine(connector.command ?? "", connector.args ?? [])
    : (connector.url ?? "HTTP endpoint not set");

const listConnectors = (init?: RequestInit) =>
  requestAgentJson(
    "/api/agent/connectors",
    Schema.decodeUnknownSync(ConnectorsResponseSchema),
    init,
  );

/** What a managed row gets instead of the editor: the facts, and no controls. */
function ManagedConnectorDrawer({
  connector,
  onClose,
}: {
  connector: ConnectorView;
  onClose: () => void;
}) {
  return (
    <ResourceDrawer
      title={connector.name}
      icon={<ResourceLogo identity={connector.id} label={connector.name} />}
      badge={
        <StatusPill tone={connector.enabled ? "good" : "default"}>
          {connector.enabled ? "enabled" : "disabled"}
        </StatusPill>
      }
      status={`${connector.origin?.kind ?? "managed"} · ${connector.origin?.id ?? connector.id}`}
      footer={<Button onClick={onClose}>Done</Button>}
      onClose={onClose}
    >
      <p className="mb-6 text-[length:var(--fs-base)] leading-relaxed text-(--ui-muted)">
        This connector is generated from a signed-in account. Its address and its tool list are
        rewritten from that account every time they are read, so there is nothing here to edit —
        change it by changing the account.
      </p>
      <ResourceDrawerSection title="Identity">
        <ResourceFact label="Connector ID" value={connector.id} mono />
        <ResourceFact label="Transport" value={connector.transport} mono />
        <ResourceFact label="Reaches" value={connectorCommand(connector)} mono />
        <ResourceFact
          label="Allowed tools"
          value={connector.allowTools?.join(" · ") || "All declared tools"}
          mono
        />
      </ResourceDrawerSection>
    </ResourceDrawer>
  );
}

function ConnectorRow({
  connector,
  onOpen,
  onChanged,
}: {
  connector: ConnectorView;
  onOpen: () => void;
  onChanged: (connectors: readonly ConnectorView[]) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [rowError, setRowError] = useState("");

  const run = (url: string, init: RequestInit, failure: string) => {
    setBusy(true);
    setRowError("");
    void requestAgentJson(url, Schema.decodeUnknownSync(ConnectorsResponseSchema), init)
      .then(({ connectors }) => onChanged(connectors))
      .catch((error: unknown) => setRowError(error instanceof Error ? error.message : failure))
      .finally(() => setBusy(false));
  };

  // Toggling re-sends the row as the server handed it over, masked secrets and
  // all: `••••••••` is the token that means "keep what you have stored", so a
  // one-field change never has to know the values it is not touching.
  const toggle = () =>
    run(
      "/api/agent/connectors",
      jsonBody({
        id: connector.id,
        name: connector.name,
        transport: connector.transport,
        command: connector.command,
        args: connector.args,
        cwd: connector.cwd,
        url: connector.url,
        env: connector.env,
        headers: connector.headers,
        allowTools: connector.allowTools,
        enabled: !connector.enabled,
      }),
      "Connector update failed",
    );

  const remove = () =>
    run(
      `/api/agent/connectors?id=${encodeURIComponent(connector.id)}`,
      { method: "DELETE" },
      "Removal failed",
    );

  return (
    <DataRow onOpen={onOpen} ariaLabel={`Open ${connector.name}`}>
      <IdentityCell
        leading={<ResourceLogo identity={connector.id} label={connector.name} />}
        label={connector.name}
        description={
          rowError ||
          (connector.origin
            ? `${connector.origin.kind} · ${connector.origin.id}`
            : `${connector.transport} · ${connector.id}`)
        }
      />
      <TextCell mono title={connectorCommand(connector)}>
        {connectorCommand(connector)}
      </TextCell>
      <EndCell>
        <div className="flex items-center justify-end gap-2">
          <StatusText tone={connector.enabled ? "ok" : "dim"}>
            {connector.enabled ? "enabled" : "disabled"}
          </StatusText>
          {busy ? <Spinner size="xs" /> : null}
          {/* Enable/disable applies to every connector, managed or not: turning
              an account's tools off is exactly what you come here to do. Only
              Remove is gated — a connector generated by a connected account is
              removed by disconnecting that account, not from this row. */}
          <RowAction
            alwaysVisible
            disabled={busy}
            onClick={toggle}
            title={
              connector.enabled
                ? "Stop offering these tools to the model"
                : "Offer these tools to the model from your next message"
            }
          >
            {connector.enabled ? "Disable" : "Enable"}
          </RowAction>
          {connector.origin ? null : (
            <RowAction
              alwaysVisible
              disabled={busy}
              onClick={remove}
              tone="danger"
              title={`Remove ${connector.name}`}
            >
              <Trash2 className="h-3 w-3" />
            </RowAction>
          )}
        </div>
      </EndCell>
    </DataRow>
  );
}

type Editing = { draft: ConnectorDraft; mode: "create" | "edit"; secretKeys: readonly string[] };

export function ConnectorsSection() {
  const [connectors, setConnectors] = useState<readonly ConnectorView[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [query, setQuery] = useState("");
  const [editing, setEditing] = useState<Editing | null>(null);
  const [managed, setManaged] = useState<ConnectorView | null>(null);
  const [oauthEntry, setOauthEntry] = useState<CatalogEntry | null>(null);

  const refresh = useCallback(() => {
    setRefreshing(true);
    void listConnectors()
      .then(({ connectors: list }) => setConnectors(list))
      .catch(() => setConnectors([]))
      .finally(() => {
        setLoaded(true);
        setRefreshing(false);
      });
  }, []);

  useMountSubscription(() => {
    refresh();
  }, [refresh]);

  const open = (connector: ConnectorView) => {
    if (connector.origin) {
      setManaged(connector);
      return;
    }
    // An OAuth-capable catalog id always opens the Connect surface, even when
    // a row already exists: the row is an artifact of connecting, and the only
    // credential decision it holds — the grant — is managed there, never in
    // the env-field editor.
    const oauthCatalog = CONNECTOR_CATALOG.find(
      (entry) => entry.auth && entry.id === connector.id,
    );
    if (oauthCatalog) {
      setOauthEntry(oauthCatalog);
      return;
    }
    setEditing({
      draft: draftFromConnector(connector),
      mode: "edit",
      secretKeys: connector.secret_keys,
    });
  };

  const openCatalogEntry = (entry: CatalogEntry) => {
    if (entry.auth) {
      setOauthEntry(entry);
      return;
    }
    const installed = connectors.find((connector) => connector.id === entry.id);
    if (installed) {
      open(installed);
      return;
    }
    // The bundled SSH server's path differs between a checkout and a signed
    // build, so it is resolved before the form opens rather than substituted
    // behind the user's back at save time — the preview has to show the real
    // argv, not a placeholder.
    void resolveSshServerPath()
      .catch(() => null)
      .then((path) =>
        setEditing({ draft: draftFromCatalog(entry, path), mode: "create", secretKeys: [] }),
      );
  };

  const normalized = query.trim().toLowerCase();
  const visibleConnectors = useMemo(
    () =>
      connectors.filter(
        (connector) =>
          connector.origin?.kind !== "account-adapter" &&
          (!normalized ||
            `${connector.name} ${connector.id} ${connectorCommand(connector)}`
              .toLowerCase()
              .includes(normalized)),
      ),
    [connectors, normalized],
  );
  const visibleCatalog = CONNECTOR_CATALOG.filter(
    (entry) =>
      !normalized ||
      `${entry.name} ${entry.company} ${entry.description}`.toLowerCase().includes(normalized),
  );

  return (
    <div className="space-y-7">
      <TableSection
        title="MCP servers"
        description="Programs and endpoints that hand the model extra tools. Each one runs on this machine."
        actions={
          <div className="flex items-center gap-2">
            <SearchInput
              value={query}
              onChange={setQuery}
              placeholder="Search servers"
              className="w-56"
            />
            <StatusText tone={loaded ? "ok" : "dim"}>
              {loaded ? `${visibleConnectors.length} registered` : "reading"}
            </StatusText>
            <RefreshIconButton onClick={refresh} loading={refreshing} label="Reload MCP servers" />
            <Button
              size="sm"
              onClick={() => setEditing({ draft: emptyDraft(), mode: "create", secretKeys: [] })}
            >
              <Plus className="h-3.5 w-3.5" />
              Add server
            </Button>
          </div>
        }
      >
        {loaded && visibleConnectors.length === 0 ? (
          <TableNotice
            title={
              connectors.length ? "No server matches this search" : "No MCP servers registered"
            }
            body="An MCP server is a command this machine runs, or an HTTP endpoint it calls, that hands the model a set of tools. Write one yourself with Add server, or start from an entry below."
          />
        ) : (
          <TableFrame minWidthClass={CONNECTOR_MIN_WIDTH}>
            <thead>
              <tr>
                <HeadCell>Server</HeadCell>
                <HeadCell title="Exactly what this row launches or calls">Runs</HeadCell>
                <HeadCell numeric>State</HeadCell>
              </tr>
            </thead>
            <tbody>
              {visibleConnectors.map((connector) => (
                <ConnectorRow
                  key={connector.id}
                  connector={connector}
                  onOpen={() => open(connector)}
                  onChanged={setConnectors}
                />
              ))}
            </tbody>
          </TableFrame>
        )}
      </TableSection>

      <TableSection
        title="Start from a known configuration"
        description="Launch configurations that ship with Local Studio. Picking one fills the form — it installs nothing and downloads nothing."
        actions={<StatusText>{`${visibleCatalog.length} configurations`}</StatusText>}
      >
        {visibleCatalog.length === 0 ? (
          <TableNotice
            title="No configuration matches this search"
            body="These are the launch configurations Local Studio ships with. Clear the search to see them all."
          />
        ) : (
          <TableFrame minWidthClass={CONNECTOR_MIN_WIDTH}>
            <thead>
              <tr>
                <HeadCell>Configuration</HeadCell>
                <HeadCell>Runs</HeadCell>
                <HeadCell numeric>State</HeadCell>
              </tr>
            </thead>
            <tbody>
              {visibleCatalog.map((entry) => {
                const installed = connectors.some((connector) => connector.id === entry.id);
                const commandLine = renderCommandLine(entry.command, entry.args);
                return (
                  <DataRow
                    key={entry.id}
                    onOpen={() => openCatalogEntry(entry)}
                    ariaLabel={`Open ${entry.name}`}
                  >
                    <IdentityCell
                      leading={
                        <ResourceLogo
                          identity={entry.id}
                          label={entry.name}
                          company={entry.company}
                        />
                      }
                      label={entry.name}
                      description={`${entry.company} · ${entry.description}`}
                    />
                    <TextCell mono title={commandLine}>
                      {commandLine}
                    </TextCell>
                    <EndCell>
                      <div className="flex items-center justify-end gap-2">
                        <StatusText tone={installed ? "ok" : "dim"}>
                          {installed ? "registered" : "not added"}
                        </StatusText>
                        <RowAction
                          alwaysVisible
                          onClick={() => openCatalogEntry(entry)}
                          title={
                            entry.auth
                              ? `Connect ${entry.name} with ${entry.company} sign-in`
                              : installed
                                ? `Open ${entry.name}`
                                : `Review ${entry.name} before adding it`
                          }
                        >
                          {entry.auth ? (
                            installed ? "Open" : "Connect"
                          ) : installed ? (
                            "Open"
                          ) : (
                            <>
                              <Plus className="h-3 w-3" />
                              Review
                            </>
                          )}
                        </RowAction>
                      </div>
                    </EndCell>
                  </DataRow>
                );
              })}
            </tbody>
          </TableFrame>
        )}
      </TableSection>

      {editing ? (
        <ConnectorEditorDrawer
          draft={editing.draft}
          mode={editing.mode}
          takenIds={connectors.map((connector) => connector.id)}
          secretKeys={editing.secretKeys}
          onClose={() => setEditing(null)}
          onChanged={setConnectors}
        />
      ) : null}
      {managed ? (
        <ManagedConnectorDrawer connector={managed} onClose={() => setManaged(null)} />
      ) : null}
      {oauthEntry ? (
        <ConnectorOAuthDrawer
          entry={oauthEntry}
          connector={connectors.find((connector) => connector.id === oauthEntry.id) ?? null}
          onClose={() => setOauthEntry(null)}
          onChanged={setConnectors}
        />
      ) : null}
    </div>
  );
}
