/**
 * Central icon barrel — the single import source for all icons in the app.
 *
 * Re-exports every lucide-react icon used across the codebase plus the custom
 * solid SVG set from icons.tsx. All files should import from here instead of
 * directly from "lucide-react", so the visual style can be changed in one place.
 */
export type { LucideIcon } from "lucide-react";

// Custom solid SVG icons (agent surface)
export {
  ChatIcon,
  PlusIcon,
  CloseIcon,
  TrashIcon,
  ChevronDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ReloadIcon,
  StopIcon,
  FileIcon,
  GlobeIcon,
  GitBranchIcon,
  UserBrowserIcon,
  PanelIcon,
  MoreIcon,
  PinIcon,
  PinOffIcon,
  Folder,
  FolderOpen,
  StatusIcon,
  ModelsIcon,
  AutomationsIcon,
  IntegrationsIcon,
  ConfigureIcon,
  UsageIcon,
  NewTaskIcon,
  SettingsIcon,
  SearchIcon,
  BellIcon,
} from "./icons";

// Sidebar toggles — see panel-toggle-icons.tsx for why these are not lucide's.
export {
  PanelLeftFilled,
  PanelLeftHollow,
  PanelRightFilled,
  PanelRightHollow,
} from "./panel-toggle-icons";

// Lucide-react re-exports — all icons used across the app
export {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDownUp,
  ArrowUp,
  ArrowUpCircle,
  AtSign,
  Bot,
  Boxes,
  Brain,
  Cable,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CornerDownRight,
  CircleDot,
  Clock,
  Code,
  Copy,
  Cpu,
  Database,
  Download,
  DownloadCloud,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FilePenLine,
  FileText,
  Filter,
  FolderTree,
  Gauge,
  GitBranch,
  GitFork,
  Globe,
  Globe2,
  HardDrive,
  GraduationCap,
  Heart,
  Info,
  Laptop,
  Layers,
  Keyboard,
  KeyRound,
  Link,
  ListChecks,
  Loader2,
  LogOut,
  Menu,
  MessageSquare,
  MessageSquarePlus,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  Network,
  Paintbrush,
  PanelRight,
  Pause,
  Pin,
  Play,
  Plus,
  RefreshCw,
  Rocket,
  RotateCcw,
  Save,
  Search,
  Server,
  ServerCog,
  Settings,
  ShieldCheck,
  Slash,
  Smartphone,
  Sparkles,
  Square,
  SquarePen,
  Sun,
  Target,
  Terminal,
  TerminalSquare,
  TriangleAlert,
  Trash2,
  Upload,
  Variable,
  Wrench,
  X,
  XCircle,
  Zap,
  Plug,
  Puzzle,
} from "lucide-react";
